from enum import Enum


class RequestCategory(Enum):
    GENERAL_CHAT = "GENERAL_CHAT"
    COMPANY_KNOWLEDGE = "COMPANY_KNOWLEDGE"
    DOCUMENT_QUERY = "DOCUMENT_QUERY"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    IMAGE_ANALYSIS = "IMAGE_ANALYSIS"
    MEETING = "MEETING"
    TASK_ASSISTANT = "TASK_ASSISTANT"
    FINANCE = "FINANCE"
    RECOMMENDATION = "RECOMMENDATION"
    UNKNOWN = "UNKNOWN"
