_SUGGESTIONS: dict[str, str] = {
    "create_project": "Would you like to create the first task for this project?",
    "delete_project": "Would you like to review your remaining projects?",
    "rename_project": "You can update team members or create tasks next.",
    "create_task": "Would you like to set a deadline or assign this task?",
    "complete_task": "Would you like to review your remaining tasks?",
    "update_task": "You can mark it complete or change the deadline next.",
    "delete_task": "Would you like to create a replacement task?",
    "change_deadline": "Would you like to review all task deadlines?",
    "change_priority": "Would you like to review all task priorities?",
    "assign_task": "The assignee has been notified.",
    "add_meeting": "Would you like me to create reminders for this meeting?",
    "cancel_meeting": "Would you like to reschedule or create a new meeting?",
    "reschedule_meeting": "The updated time has been saved.",
    "rename_meeting": "Meeting renamed successfully.",
    "add_reminder": "You can set additional reminders if needed.",
    "create_notification": "The notification has been sent.",
    "mark_as_read": "You can view your remaining notifications.",
    "show_meetings": "Would you like to see details for any specific meeting?",
    "today_meetings": "Would you like to see details for any of these meetings?",
    "upcoming_meetings": "Would you like to see details for any specific meeting?",
    "show_meeting_detail": "Would you like to update this meeting or add participants?",
    "add_participant": "Would you like to add more participants?",
    "remove_participant": "Would you like to review the remaining participants?",
    "upload_mom": "Would you like me to analyze the MOM for tasks and decisions?",
    "analyze_mom": "Would you like to approve the extracted tasks?",
    "extract_tasks_from_mom": "Would you like to approve the extracted tasks?",
    "show_extracted_tasks": "Would you like to approve or reject any of these tasks?",
    "approve_extracted_tasks": "The tasks have been approved and added to the task board.",
    "reject_extracted_tasks": "The tasks have been rejected.",
    "accept_meeting": "You've accepted the meeting. Would you like to add it to your calendar?",
    "decline_meeting": "You've declined the meeting. Would you like to suggest an alternative time?",
    "who_accepted": "Would you like to send a reminder to those who haven't responded?",
    "who_declined": "Would you like to suggest an alternative time for those who declined?",
    "show_meeting_timeline": "Would you like to see the MOM analysis or extracted tasks?",
    "show_meeting_decisions": "Would you like to see the risks or follow-ups for this meeting?",
    "show_meeting_risks": "Would you like to see the decisions or follow-ups for this meeting?",
    "show_meeting_followups": "Would you like to see the decisions or risks for this meeting?",
    "show_meeting_blockers": "Would you like to see the decisions or follow-ups for this meeting?",
}


def get_suggestion(intent_value: str) -> str:
    return _SUGGESTIONS.get(intent_value, "")
