_SUGGESTIONS: dict[str, str] = {
    "create_project": "Would you like to create the first task for this project?",
    "delete_project": "Would you like to review your remaining projects?",
    "rename_project": "You can update team members or create tasks next.",
    "create_task": "Would you like to set a deadline or assign this task?",
    "complete_task": "Would you like to review your remaining tasks?",
    "update_task": "You can mark it complete or change the deadline next.",
    "delete_task": "Would you like to create a replacement task?",
    "change_deadline": "Would you like to review all task deadlines?",
    "change_priority": "Would you like to review all task priorities?",
    "assign_task": "The assignee has been notified.",
    "add_meeting": "Would you like me to create reminders for this meeting?",
    "cancel_meeting": "Would you like to reschedule or create a new meeting?",
    "reschedule_meeting": "The updated time has been saved.",
    "rename_meeting": "Meeting name updated successfully.",
    "add_participant": "The participant has been invited.",
    "remove_participant": "The participant has been removed.",
    "show_meeting_detail": "Would you like to upload MOM or view the timeline?",
    "add_reminder": "You can set additional reminders if needed.",
    "upload_mom": "You can now extract tasks or analyze the MOM from this meeting.",
    "analyze_mom": "Would you like to extract tasks from this MOM?",
    "extract_tasks_from_mom": "Would you like me to approve or reject these extracted tasks?",
    "show_extracted_tasks": "Would you like to approve or reject any of these tasks?",
    "approve_extracted_tasks": "Tasks have been created. Would you like to assign them?",
    "reject_extracted_tasks": "Rejected tasks have been dismissed.",
    "who_accepted": "Would you like to see who declined as well?",
    "who_declined": "Would you like to see who accepted?",
    "accept_meeting": "Great! You've confirmed your attendance.",
    "decline_meeting": "The meeting host has been notified.",
    "show_meetings": "Would you like to see today's meetings or upcoming ones?",
    "today_meetings": "Would you like to accept or decline any invitations?",
    "upcoming_meetings": "Would you like more details on any of these meetings?",
    "show_meeting_timeline": "Would you like to upload MOM or add notes?",
    "show_meeting_decisions": "Would you like to see the risks or follow-ups too?",
    "show_meeting_risks": "Would you like to see the blockers or follow-ups?",
    "show_meeting_followups": "Would you like to see the decisions or risks?",
    "show_meeting_blockers": "Would you like to see the risks or follow-ups?",
    "create_notification": "The notification has been sent.",
    "mark_as_read": "You can view your remaining notifications.",
}


def get_suggestion(intent_value: str) -> str:
    return _SUGGESTIONS.get(intent_value, "")
